# Generated by Django 5.2.10 on 2026-02-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pontos_valem', models.IntegerField()),
                ('resposta_correta', models.CharField(blank=True, max_length=100, null=True)),
                ('data_limite', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=3)),
                ('grupo', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H'), ('I', 'Grupo I'), ('J', 'Grupo J'), ('K', 'Grupo K'), ('L', 'Grupo L')], max_length=1)),
                ('imagem', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jogo', models.IntegerField(unique=True)),
                ('gols_casa', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
                ('fase', models.CharField(choices=[('GRUPOS', 'Fase de Grupos'), ('16AVOS', '16-avos de Final'), ('OITAVAS', 'Oitavas de Final'), ('QUARTAS', 'Quartas de Final'), ('SEMI', 'Semi-Final'), ('FINAL', 'Final')], max_length=20)),
                ('data_jogo', models.DateTimeField()),
                ('referencia_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('referencia_visitante', models.CharField(blank=True, max_length=10, null=True)),
                ('time_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casa', to='bolao.time')),
                ('time_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitante', to='bolao.time')),
            ],
        ),
        migrations.CreateModel(
            name='PalpitePodium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_campeao', models.IntegerField(default=0)),
                ('pontos_vice', models.IntegerField(default=0)),
                ('pontos_terceiro', models.IntegerField(default=0)),
                ('pontos_quarto', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campeao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aposta_campeao', to='bolao.time')),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aposta_quarto', to='bolao.time')),
                ('terceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aposta_terceiro', to='bolao.time')),
                ('vice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aposta_vice', to='bolao.time')),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palpite_casa', models.IntegerField()),
                ('palpite_visitante', models.IntegerField()),
                ('pontos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.partida')),
            ],
            options={
                'unique_together': {('usuario', 'partida')},
            },
        ),
        migrations.CreateModel(
            name='PalpiteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_usuario', models.CharField(max_length=100)),
                ('pontos_ganhos', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.perguntaextra')),
            ],
            options={
                'unique_together': {('usuario', 'pergunta')},
            },
        ),
    ]
